### PR TITLE
only pull in used lodash methods for 60k of savings :)

### PR DESCRIPTION
**Pull request by lukechinworth**
also removed option to pass configure multiple options objects. merge them yoself.

### CODE REVIEW

**Comment by Duder-onomy** [comment]
YEAH!  Might want to close this one now: #1

**Comment by lukechinworth** [comment]
@Duder-onomy can you publish on npm, and/or add me as a maintainer? Thanks, Greg.

**Comment by Duder-onomy** [comment]
@lukechinworth Yeah! Totally. Thanks for working on it. Im at the city dump right now but will add you as soon as i get into the office. I also have a fork of this that you might be interested in cherry picking some features depending on what your doing with it. The fork attempts to find focusable elements based on an elements interactivity. Starting with anchors and buttons, then aria roles, then testing for any attached handlers, with a final fallback to a filter function you can define. Basically, it makes the page interactive without explicitly opting into focusability. Its aight. Need to tweak the azimuth and distance logic. But yeah. Ill add you as soon as i get to my comp.

**Comment by Duder-onomy** [comment]
@lukechinworth What is your NPM username? Your avatar does not show up with your Github username, just wanted to check so I don't accidentally add a stranger

**Comment by lukechinworth** [comment]
my npm is lukechinworth

**Comment by Duder-onomy** [comment]
Ok, cool. Your in there now: 
image

Let me know if there is anything I can help with.

**Comment by lukechinworth** [comment]
@Duder-onomy tight! thanks

**Pull request merged**
